// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtXf-I55El4zbcWRdz_GiEJC_sbqJLSE',
    appId: '1:227174001275:web:921685a5d934bafef210de',
    messagingSenderId: '227174001275',
    projectId: 'tasky-d75fa',
    authDomain: 'tasky-d75fa.firebaseapp.com',
    storageBucket: 'tasky-d75fa.firebasestorage.app',
    measurementId: 'G-B2PLKM5Q9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpnJx6I4bXuQLqHB7get24c9q1HeqbAwg',
    appId: '1:227174001275:android:e0b3f4dcd85d57e1f210de',
    messagingSenderId: '227174001275',
    projectId: 'tasky-d75fa',
    storageBucket: 'tasky-d75fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5NChe3hOAHUP9DZyz8McJ_ZTwaOzaFn4',
    appId: '1:227174001275:ios:065d67575c9e48f6f210de',
    messagingSenderId: '227174001275',
    projectId: 'tasky-d75fa',
    storageBucket: 'tasky-d75fa.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5NChe3hOAHUP9DZyz8McJ_ZTwaOzaFn4',
    appId: '1:227174001275:ios:065d67575c9e48f6f210de',
    messagingSenderId: '227174001275',
    projectId: 'tasky-d75fa',
    storageBucket: 'tasky-d75fa.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgtXf-I55El4zbcWRdz_GiEJC_sbqJLSE',
    appId: '1:227174001275:web:8c9ebae6a7071dedf210de',
    messagingSenderId: '227174001275',
    projectId: 'tasky-d75fa',
    authDomain: 'tasky-d75fa.firebaseapp.com',
    storageBucket: 'tasky-d75fa.firebasestorage.app',
    measurementId: 'G-MRHH8PKKPF',
  );
}
